version : "3.1"
services: 
  db:
    container_name: mysqldb
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3307
    env_file:
      - docker.env
    volumes:
        - ./data/mysql-data:/var/lib/mysql
    networks:
      - nestjs-network

  adminer: 
    image: adminer
    restart: always
    ports: 
      - 8888:8080
    networks:
      - nestjs-network

  api:
    image: nestjs-backend
    container_name: nestjs-api
    depends_on: 
      - db
    ports:
      - 3000:3000
    networks: 
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
