version : "3.1"
services: 
  db:
    container_name: mysqldb
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
        - ./data/mysql-data:/var/lib/mysql
    networks:
      - nestjs-network

  adminer: 
    container_name: exlibris-adminer
    image: adminer
    restart: always
    ports: 
      - 8888:8080
    networks:
      - nestjs-network

  api:
    container_name: exlibris-nestjs-api
    image: exlibris-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - db
    environment:
      - MYSQL_HOST=
      - MYSQL_PORT=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MODE=DEV
      - SECRET=
    ports:
      - 33000:3000
    networks: 
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
