#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = http://localhost:33000

# ============================================================================
#    Entity: Livro
#    Endpoint: /livro
# ============================================================================

####
#### Selects all livros 
#### 
GET {{hostname}}/livros HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Create a new livro 
#### 
POST {{hostname}}/livros HTTP/1.1
X-API-Key: 
Content-Type: application/json

[
{
    "titulo": "Anne of Green Gables",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "L M Montgomery",
    "siglaISOIdioma": "en",
    "edicao": "1",
    "cidade": "Kensignton",
    "ano": 2022,
    "genero": "Literatura; Literatura canadense; Prince Edward Island; Green Gables",
    "editora": "Kindred Spirits of PEI Publishing",
    "colecao": "",
    "status": "C",
    "isbn": "978-0-9959507-0-2",
    "paginas": 311,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "Edição feita pela família da autora; autografado pelo filho de LM Montgomery para Alice"
  }
]

####
#### Create a new batch of livros 
#### 
POST {{hostname}}/livros HTTP/1.1
X-API-Key: 
Content-Type: application/json

[
  {
    "codigo": 1,
    "titulo": "Meu eterno amor, meu Papai!",
    "subtitulo": "",
    "tituloOriginal": "Meu eterno amor, meu Papai!",
    "autores": "Alice Morais Torres; Edjara Rodirgues Morais",
    "siglaISOIdioma": "pt",
    "edicao": "",
    "cidade": "Québec City",
    "ano": 2022,
    "genero": "Amor; Família",
    "editora": "Costco Photo Center",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 2,
    "titulo": "Edgar Allan Poe",
    "subtitulo": "",
    "tituloOriginal": "Edgar Allan Poe",
    "autores": "Edgar Allan Poe",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "New York",
    "ano": 1945,
    "genero": "Literatura; Fantasia; Horror; Gótico",
    "editora": "Viking Press",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": true,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 3,
    "titulo": "La Bible de Jérusalem",
    "subtitulo": "La Sainte Bible Traduite en français sous la direction de l'École Biblique de Jérusalem",
    "tituloOriginal": "La Bible de Jérusalem",
    "autores": "Various",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1986,
    "genero": "Religião; Católico; Bíblia",
    "editora": "Desclée de Brouwer",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 4,
    "titulo": "Le Rosaire",
    "subtitulo": "Nouvelle édition augmentée des cinq mystères lumineux",
    "tituloOriginal": "Le Rosaire",
    "autores": "R.P.J.M. Lelen, Ph.D.",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "New Jersey",
    "ano": 2013,
    "genero": "Religião; Católico; Rosário",
    "editora": "Catholic Book Publishing Corp",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 5,
    "titulo": "Guide des Tertiaires de Saint François",
    "subtitulo": "",
    "tituloOriginal": "Guide des Tertiaires de Saint François",
    "autores": "Nihil",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Québec City",
    "ano": 1953,
    "genero": "Religião; Católico",
    "editora": "Tremblay & Dion Inc.",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 6,
    "titulo": "101 Jogos e Fantasias Sexuais",
    "subtitulo": "Tudo o que você precisa saber para apimentar a sua vida sexual",
    "tituloOriginal": "101 fantasias y juegos sexuales",
    "autores": "Sofia Capablanca",
    "siglaISOIdioma": "pt",
    "edicao": "",
    "cidade": "São Paulo",
    "ano": 2006,
    "genero": "Sexualidade; Sensualidade; Fantasia sexual",
    "editora": "Marco Zero",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 7,
    "titulo": "Tolkien, an Illustrated Atlas",
    "subtitulo": "",
    "tituloOriginal": "Tolkien, an Illustrated Atlas",
    "autores": "David Day",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "San Diego, CA",
    "ano": 2015,
    "genero": "Literatura; Fantasia; LotR; Tolkien",
    "editora": "Thunder Bay Press",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 8,
    "titulo": "Breviarium Romanum",
    "subtitulo": "Pars Verna",
    "tituloOriginal": "Breviarium Romanum",
    "autores": "Nihil",
    "siglaISOIdioma": "la",
    "edicao": "",
    "cidade": "Turonibus",
    "ano": 1921,
    "genero": "Religião; Católico; Breviário",
    "editora": "A. Mame et Filiorum",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": true,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 9,
    "titulo": "Manual for Men",
    "subtitulo": "",
    "tituloOriginal": "Manual for Men",
    "autores": "Thomas J. Olmsted",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Charlotte, NC",
    "ano": 2017,
    "genero": "Religião; Católico",
    "editora": "TAN Books",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 10,
    "titulo": "La Sainte Bible",
    "subtitulo": "Traduite d'aprés les textes originaux hébreu et grec, par Louis Segond, Docteur en théologie",
    "tituloOriginal": "La Sainte Bible",
    "autores": "Louis Segond",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "",
    "ano": 2023,
    "genero": "Religião; Católico; Bíblia",
    "editora": "Alliance Biblique Universelle",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 11,
    "titulo": "Mon Combat",
    "subtitulo": "",
    "tituloOriginal": "Mein Kampf",
    "autores": "Adolf Hitler",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1979,
    "genero": "Militaria; História; Guerra; Nazismo; Textos fundamentais",
    "editora": "Nouvelles Éditions Latines",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 12,
    "titulo": "The Chess Player's Handbook",
    "subtitulo": "A popular and scientific introduction to the game of chess, exemplified in games actually played by the greatest maseters and illustrated by numerous diagrams of original and remarkable positions",
    "tituloOriginal": "The Chess Player's Handbook",
    "autores": "Howard Staunton, Esq.",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "London",
    "ano": 1848,
    "genero": "Esporte; Xadrez; Manual",
    "editora": "Henry G. Bohn",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": true,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 13,
    "titulo": "Tales of Edgar Allan Poe",
    "subtitulo": "With an introduction by Hervey Allen and wood engravings by Fritz Eichenberg",
    "tituloOriginal": "Tales of Edgar Allan Poe",
    "autores": "Edgar Allan Poe",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "New York",
    "ano": 1949,
    "genero": "Literatura; Fantasia; Horror; Gótico",
    "editora": "Random House, Inc.",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": true,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 14,
    "titulo": "Leaving boyhood behind",
    "subtitulo": "Reclaiming Catholic Brotherhood",
    "tituloOriginal": "Leaving boyhood behind",
    "autores": "Jason M. Craig",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Huntington, IN",
    "ano": 2019,
    "genero": "Religião; Católico; Fraternidade",
    "editora": "Our Sunday Visitor Publishing Division",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 15,
    "titulo": "Introduçao a Criptografia",
    "subtitulo": "",
    "tituloOriginal": "Introduction to Cryptography",
    "autores": "Johannes A. Buchmann",
    "siglaISOIdioma": "pt",
    "edicao": "",
    "cidade": "São Paulo",
    "ano": 2002,
    "genero": "Computação; Criptografia; Processamento de dados; Segurança",
    "editora": "Editora Berkley",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 16,
    "titulo": "Beginning NFC",
    "subtitulo": "Near Field Communication with Arduino, Android & PhoneGAP",
    "tituloOriginal": "Beginning NFC",
    "autores": "Tom Igoe; Don Coleman; Brian Jepson",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Sebastopol, CA",
    "ano": 2014,
    "genero": "Computação; NFC; Arduino; Android; PhoneGAP; Radio",
    "editora": "O'Reilly Media, Inc.",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 17,
    "titulo": "Journaux de Guerre",
    "subtitulo": "I. 1914-1918",
    "tituloOriginal": "Journaux de Guerre",
    "autores": "Ernst Jünger",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2008,
    "genero": "Militaria; I Guerra Mundial; Jornal íntimo; POV Alemão",
    "editora": "Éditions Gallimard",
    "colecao": "Bibliothèque de la Pléiade",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 18,
    "titulo": "Airband Radio on the RTL-SDR",
    "subtitulo": "Tips and tricks for capturing voice and data on a revolutionary device",
    "tituloOriginal": "Airband Radio on the RTL-SDR",
    "autores": "Philip G. Collier",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Bolton, ON",
    "ano": 2021,
    "genero": "Radio; RTL; SDR",
    "editora": "Amazon.ca",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 19,
    "titulo": "Jacques de Molay",
    "subtitulo": "Le dernier grand-maître des Templiers",
    "tituloOriginal": "Jacques de Molay",
    "autores": "Philippe Josserand",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2019,
    "genero": "Templários; Biografia; Maçonaria; História",
    "editora": "Les Belles Lettres",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 20,
    "titulo": "Rituels Cathares",
    "subtitulo": "",
    "tituloOriginal": "Rituels Cathares",
    "autores": "Claude Arnoux",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Nimes",
    "ano": 1993,
    "genero": "Cátaros; Maçonaria; História; Ritualistica",
    "editora": "Lacour Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 21,
    "titulo": "Écrits Spirituels",
    "subtitulo": "",
    "tituloOriginal": "Écrits Spirituels",
    "autores": "St Charles de Foucauld",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Plouisy",
    "ano": 2007,
    "genero": "Religião; Católico; Biografia; Vida dos Santos; St Charles de Foucauld",
    "editora": "Éditions Petrus",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 22,
    "titulo": "The Cloud of Unknowing",
    "subtitulo": "And the Book of Privy Counseling",
    "tituloOriginal": "The Cloud of Unknowing",
    "autores": "Nihil",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "New York",
    "ano": 2014,
    "genero": "Religião; Católico; Espiritualidade",
    "editora": "Image Edition",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 23,
    "titulo": "Poesia completa e prosa",
    "subtitulo": "",
    "tituloOriginal": "Poesia completa e prosa",
    "autores": "Vinicuis de Moraes",
    "siglaISOIdioma": "pt",
    "edicao": "",
    "cidade": "Rio de Janeiro",
    "ano": 1981,
    "genero": "Literatura; Prosa; Poesia",
    "editora": "Editora Nova Aguilar",
    "colecao": "Biblioteca Luso-Brasileira, Série Brasileira",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 24,
    "titulo": "Orthodoxy",
    "subtitulo": "",
    "tituloOriginal": "Orthodoxy",
    "autores": "Gilberth Keith Chesterton",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Nashville, TN",
    "ano": 2022,
    "genero": "Religião; Cristianismo; Apologética; Teologia; Doutrina",
    "editora": "B&H Academic",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 25,
    "titulo": "Structured Fortran 77 for Engineers and Scientists",
    "subtitulo": "",
    "tituloOriginal": "Structured Fortran 77 for Engineers and Scientists",
    "autores": "D.M. Etter",
    "siglaISOIdioma": "en",
    "edicao": "",
    "cidade": "Redwood City, CA",
    "ano": 1993,
    "genero": "Computação; Programação; Fortran",
    "editora": "The Benjamin/Cummings Publishing Company, Inc.",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 26,
    "titulo": "Como vencer um debate sem precisar ter razao",
    "subtitulo": "Em 38 estratagemas (Dialética Eristica)",
    "tituloOriginal": "",
    "autores": "Arthur Schopenhauer",
    "siglaISOIdioma": "pt",
    "edicao": "0",
    "cidade": "Rio de Janeiro, RJ",
    "ano": 2003,
    "genero": "Filosofia; Filosofia Alemã; Dialética Erística",
    "editora": "Topbooks",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 27,
    "titulo": "L'Histoire et ses méthodes",
    "subtitulo": "Recherche, conservation et critique des témoignages, sous la direction de Charles Samarand, de l'Institut",
    "tituloOriginal": "L'Histoire et ses méthodes",
    "autores": "Charles Samarand",
    "siglaISOIdioma": "fr",
    "edicao": "0",
    "cidade": "Paris",
    "ano": 1963,
    "genero": "História; Metodologia; Pesquisa; Conservação",
    "editora": "Éditions Gallimard",
    "colecao": "Encyclopédie de la Pléiade",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 28,
    "titulo": "The First Six books of The Elements of Euclid",
    "subtitulo": "",
    "tituloOriginal": "The First Six books of The Elements of Euclid",
    "autores": "Oliver Byrne",
    "siglaISOIdioma": "en",
    "edicao": "0",
    "cidade": "Köln",
    "ano": 0,
    "genero": "Geometria; Matemática; Clássico; Maçonaria",
    "editora": "Taschen",
    "colecao": "Bibliotheca Universalis",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 29,
    "titulo": "Orthodoxie Maçonnique",
    "subtitulo": "Suivie de la Maçonnerie Occulte et de l'Initiation Hermetique",
    "tituloOriginal": "",
    "autores": "Jean-Marie Ragon",
    "siglaISOIdioma": "fr",
    "edicao": "0",
    "cidade": "Paris",
    "ano": 1853,
    "genero": "Maçonaria; Dogma; Ritualistica; Ortodoxia",
    "editora": "E. Dentu, Libraire-Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": true,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 30,
    "titulo": "Devocionario Quotidiano",
    "subtitulo": "Coletânea de oraçoes Cristãs",
    "tituloOriginal": "",
    "autores": "Nihil",
    "siglaISOIdioma": "la;pt",
    "edicao": "0",
    "cidade": "Rio de Janeiro",
    "ano": 2020,
    "genero": "Religião; Católico; Tradição Cristã; Oração; Devoção",
    "editora": "Editora Caritatem",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 31,
    "titulo": "Les Heures de l'Office Divin",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Nihil",
    "siglaISOIdioma": "fr",
    "edicao": "0",
    "cidade": "",
    "ano": 1966,
    "genero": "Religião; Católico; Tradição Cristã; Oração; Devoção; Liturgia das Horas",
    "editora": "Imprimerie Mame",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 32,
    "titulo": "Missale Romanum",
    "subtitulo": "Ex decreto Sacrosancti Concili Tridentini restitutum Summorum Pontificum cura recognitum",
    "tituloOriginal": "",
    "autores": "Nihil",
    "siglaISOIdioma": "fr",
    "edicao": "0",
    "cidade": "Torino",
    "ano": 1963,
    "genero": "Religião; Católico; Tradição Cristã; Oração; Devoção; Missal",
    "editora": "Casa Editrice Marietti",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 33,
    "titulo": "Missal Romano Quotidiano",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Nihil",
    "siglaISOIdioma": "la;pt",
    "edicao": "0",
    "cidade": "Bruges",
    "ano": 1964,
    "genero": "Religião; Católico; Tradição Cristã; Oração; Devoção; Missal",
    "editora": "Les Presses Saint-Augustin",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-02-02T14:56:21.080Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 34,
    "titulo": "Livre d'Heures du Pafait Maçon",
    "subtitulo": "Guide en 12 points de l'initiation maçonnique regulière",
    "tituloOriginal": "",
    "autores": "Various",
    "siglaISOIdioma": "fr",
    "edicao": "0",
    "cidade": "",
    "ano": 2021,
    "genero": "Maçonaria; Iniciação; Simbolismo",
    "editora": "Éditions Scribe",
    "colecao": "Collection Villard de Honnecour",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 35,
    "titulo": "Corpus Hermeticum",
    "subtitulo": "Poimandres; Traités II-XII",
    "tituloOriginal": "",
    "autores": "Hermes Trimegisto",
    "siglaISOIdioma": "gr;fr",
    "edicao": "2",
    "cidade": "Paris",
    "ano": 2017,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 36,
    "titulo": "Discours",
    "subtitulo": "Catilinaires; Tome X",
    "tituloOriginal": "",
    "autores": "Cicéron",
    "siglaISOIdioma": "la;fr",
    "edicao": "2",
    "cidade": "Paris",
    "ano": 1957,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 37,
    "titulo": "De la Nature",
    "subtitulo": "Livres I-III",
    "tituloOriginal": "",
    "autores": "Lucrèce",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1966,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 38,
    "titulo": "La Guerre d'Afrique",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1949,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 39,
    "titulo": "La Guerre Civile",
    "subtitulo": "Livres I-II",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1965,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 40,
    "titulo": "La Guerre Civile",
    "subtitulo": "Livre III",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1964,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 41,
    "titulo": "La Guerre des Gaules",
    "subtitulo": "Livres I-IV",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2010,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 42,
    "titulo": "La Guerre des Gaules",
    "subtitulo": "Livres V-VIII",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2008,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 43,
    "titulo": "De Bello Gallico",
    "subtitulo": "commentarii",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1913,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 44,
    "titulo": "C. Iuli Caesaris Commentariorum",
    "subtitulo": "Pars prior qua continentur Libri VII de Bello Gallico",
    "tituloOriginal": "",
    "autores": "Caius Julius Caesar",
    "siglaISOIdioma": "la",
    "edicao": "",
    "cidade": "Oxford",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Oxonii E Typographeo Clarendoniano",
    "colecao": "Oxford Classical Texts",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 45,
    "titulo": "P. Vergili Maronis Opera",
    "subtitulo": "Recognovit brevique adnotatione critica instruxit",
    "tituloOriginal": "",
    "autores": "Virgilio",
    "siglaISOIdioma": "la",
    "edicao": "",
    "cidade": "Oxford",
    "ano": 1963,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Oxonii E Typographeo Clarendoniano",
    "colecao": "Oxford Classical Texts",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 46,
    "titulo": "L'Éneide",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Virgilio",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1965,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Garnier-Flammarion",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 47,
    "titulo": "Iliade; Odyssée",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Homero",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2018,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Gallimard",
    "colecao": "Bibliothèque de la Pléiade",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 48,
    "titulo": "Correspondance",
    "subtitulo": "Tome I",
    "tituloOriginal": "",
    "autores": "Cicéron",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1934,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 49,
    "titulo": "Fables",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Ésope",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 2012,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 50,
    "titulo": "Rhétorique",
    "subtitulo": "Livre II",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1960,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 51,
    "titulo": "Énéide",
    "subtitulo": "Livres I-VI",
    "tituloOriginal": "",
    "autores": "Virgile",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1964,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 52,
    "titulo": "La Guerre du Péloponnèse",
    "subtitulo": "Livre I",
    "tituloOriginal": "",
    "autores": "Thucydide",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1953,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 53,
    "titulo": "La Guerre du Péloponnèse",
    "subtitulo": "Livre II",
    "tituloOriginal": "",
    "autores": "Thucydide",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 54,
    "titulo": "Économique",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Xénophon",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1949,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 55,
    "titulo": "Histoire Romaine",
    "subtitulo": "Livre I",
    "tituloOriginal": "",
    "autores": "Tite-Live",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 56,
    "titulo": "Histoire Romaine",
    "subtitulo": "Livre II",
    "tituloOriginal": "",
    "autores": "Tite-Live",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 57,
    "titulo": "Les Métamorphoses",
    "subtitulo": "Livres VI-X",
    "tituloOriginal": "",
    "autores": "Ovide",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1955,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 58,
    "titulo": "Dialogue des Orateurs",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Tacite",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1947,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 59,
    "titulo": "Géorgiques",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Virgile",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1963,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 60,
    "titulo": "Anthologie Palatine",
    "subtitulo": "Livro VIII",
    "tituloOriginal": "",
    "autores": "Saint Grégoire",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1960,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 61,
    "titulo": "Bucoliques",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Virgile",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1956,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 62,
    "titulo": "Hippias Majeur; Charmide; Lachès; Lysis",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Platon",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1956,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 63,
    "titulo": "Poétique",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 64,
    "titulo": "Physique",
    "subtitulo": "Livres I-IV",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 65,
    "titulo": "Constitution d'Athènes",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1952,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 66,
    "titulo": "Les Suppliantes; Les Perses; Les Sept contre Thèbes; Prométhée enchainée",
    "subtitulo": "Tome I",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1963,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 67,
    "titulo": "Iliade",
    "subtitulo": "I",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 68,
    "titulo": "Iliade",
    "subtitulo": "III",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 69,
    "titulo": "L'Odyssée",
    "subtitulo": "Tome I Chants I-VII",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1955,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 70,
    "titulo": "L'Odyssée",
    "subtitulo": "Tome II Chants VIII-XV",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1959,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 71,
    "titulo": "L'Odyssée",
    "subtitulo": "Tome III Chants XVI-XXIV",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1956,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Les Belles Lettres",
    "colecao": "Collection des Universités de France; Association Guillaume Budé",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 72,
    "titulo": "Bucoliques; Géorgiques; Énéide",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Virgile",
    "siglaISOIdioma": "la;fr",
    "edicao": "9",
    "cidade": "Paris",
    "ano": 1919,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 73,
    "titulo": "De Amicitia",
    "subtitulo": "Dialogus",
    "tituloOriginal": "",
    "autores": "M. T. Ciceronis Laelius",
    "siglaISOIdioma": "la;fr",
    "edicao": "3",
    "cidade": "Paris",
    "ano": 1910,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 74,
    "titulo": "Versions Latines commentées",
    "subtitulo": "Pour les classes de Troisième, Seconde et Première",
    "tituloOriginal": "",
    "autores": "H. Petitmangin",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1947,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; Linguagem",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 75,
    "titulo": "Exercices Latins",
    "subtitulo": "Première Série Classe de 6e",
    "tituloOriginal": "",
    "autores": "H. Petitmangin",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1953,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; Linguagem",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 76,
    "titulo": "Textes Grecs du Programme",
    "subtitulo": "Classes de 5e, 4e, et 3e",
    "tituloOriginal": "",
    "autores": "H. Petitmangin",
    "siglaISOIdioma": "gr;fr",
    "edicao": "7",
    "cidade": "Paris",
    "ano": 1948,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; Linguagem",
    "editora": "J. De Gigord, Éditeur",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 77,
    "titulo": "History of the Peloponnesian War",
    "subtitulo": "Tome II Books III and IV",
    "tituloOriginal": "",
    "autores": "Thucydides",
    "siglaISOIdioma": "gr;en",
    "edicao": "",
    "cidade": "Cambridge, Mass",
    "ano": 1965,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Harvard University Press",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 78,
    "titulo": "History of the Peloponnesian War",
    "subtitulo": "Tome III Books V and VI",
    "tituloOriginal": "",
    "autores": "Thucydides",
    "siglaISOIdioma": "gr;en",
    "edicao": "",
    "cidade": "Cambridge, Mass",
    "ano": 1959,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Harvard University Press",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 79,
    "titulo": "Histoire de Rome",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "André Piganiol",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; História",
    "editora": "Presses Universitaires de France",
    "colecao": "Clio",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 80,
    "titulo": "Cours de Langue Latine",
    "subtitulo": "Grammaire complète",
    "tituloOriginal": "",
    "autores": "Léon Debeauvais",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1951,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; Linguagem",
    "editora": "Librairie Classique Eugène Belin",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 81,
    "titulo": "Histoire sommaire de la Litérature Grecque",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "H. Petitmangin",
    "siglaISOIdioma": "fr",
    "edicao": "15",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; História",
    "editora": "Librairie Classique Eugène Belin",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 82,
    "titulo": "Hannibal de Tite-Live",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Guy Michaud",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1938,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; História",
    "editora": "Librairie Hachette",
    "colecao": "Classiques Roma",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 83,
    "titulo": "Mythe et pensée chez les Grecs",
    "subtitulo": "I Études de psychologie historique",
    "tituloOriginal": "",
    "autores": "Jean-Pierre Vernant",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1971,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; História",
    "editora": "François Maspero",
    "colecao": "Petite collection Maspero",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 84,
    "titulo": "Mythe et pensée chez les Grecs",
    "subtitulo": "II Études de psychologie historique",
    "tituloOriginal": "",
    "autores": "Jean-Pierre Vernant",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1971,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga; História",
    "editora": "François Maspero",
    "colecao": "Petite collection Maspero",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 85,
    "titulo": "Lettres à Lucilius",
    "subtitulo": "(1-29)",
    "tituloOriginal": "",
    "autores": "Sénèque",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1992,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Garnier-Flammarion",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 86,
    "titulo": "Les secrets de la correspondance de Cicéron",
    "subtitulo": "Tome Premier",
    "tituloOriginal": "",
    "autores": "Jérôme Carcopino",
    "siglaISOIdioma": "fr",
    "edicao": "9",
    "cidade": "Paris",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "L'Artisan du Livre",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 87,
    "titulo": "Les secrets de la correspondance de Cicéron",
    "subtitulo": "Tome Second",
    "tituloOriginal": "",
    "autores": "Jérôme Carcopino",
    "siglaISOIdioma": "fr",
    "edicao": "8",
    "cidade": "Paris",
    "ano": 1962,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "L'Artisan du Livre",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 88,
    "titulo": "L'Odyssée",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Homère",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1954,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 89,
    "titulo": "Brutus",
    "subtitulo": "La perfection oratoire",
    "tituloOriginal": "",
    "autores": "Cicéron",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1934,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 90,
    "titulo": "Lettres à Lucilius",
    "subtitulo": "III Lettres XCIII à CLVI",
    "tituloOriginal": "",
    "autores": "Sénèque",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1954,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 91,
    "titulo": "Lettres à Lucilius",
    "subtitulo": "II Lettres LXVI à XCII",
    "tituloOriginal": "",
    "autores": "Sénèque",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1955,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 92,
    "titulo": "Conjuration de Catilina; Guerre de Jugurtha; Fragments des Histoires",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Salluste",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1947,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 93,
    "titulo": "Dialogues des orateurs; Vie d'Agricola; La Germanie",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Tacite",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1949,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 94,
    "titulo": "Considerations sur les causes de la Grandeur des Romains et de leur Décadence",
    "subtitulo": "Le dialogue de Sylla et d'Eucrate, Lysimaque. Dissertation sur la politique des romains dans la réligion. Le discours sur Cicéron. Remarques sur certaines objections",
    "tituloOriginal": "",
    "autores": "Montesquieu",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1954,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 95,
    "titulo": "Histoire de la Guerre du Peloponnèse",
    "subtitulo": "Complète",
    "tituloOriginal": "",
    "autores": "Thucydide",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1948,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 96,
    "titulo": "Éthique de Nicomaque",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Aristote",
    "siglaISOIdioma": "gr;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 97,
    "titulo": "La Divine Comédie",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Dante",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 0,
    "genero": "Clássico; Classicismo; Italiano; Literatura",
    "editora": "Éditions Garnier Frères",
    "colecao": "Classiques Garnier",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 98,
    "titulo": "Les damnés de la terre",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "Frantz Fanon",
    "siglaISOIdioma": "fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1970,
    "genero": "Ciência Social; Sociologia; História; Descolonização",
    "editora": "François Maspero",
    "colecao": "Petite collection Maspero",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 99,
    "titulo": "Carta Enciclica Fides et Ratio",
    "subtitulo": "do Sumo Pontífice João Paulo II aos bispos da Igreja Católica sobre as relações entre a fé e a razao",
    "tituloOriginal": "",
    "autores": "São João Paulo II",
    "siglaISOIdioma": "pt",
    "edicao": "",
    "cidade": "São Paulo",
    "ano": 2001,
    "genero": "Religião; Católico; Catolicismo; Carta Enciclica; Filosofia; Fé; Razao",
    "editora": "Paulinas",
    "colecao": "",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  },
  {
    "codigo": 100,
    "titulo": "Lettres Latines",
    "subtitulo": "",
    "tituloOriginal": "",
    "autores": "R. Morisser; G. Thévenot",
    "siglaISOIdioma": "la;fr",
    "edicao": "",
    "cidade": "Paris",
    "ano": 1961,
    "genero": "Clássico; Classicismo; Greco-Romano; Grécia Antiga; Roma Antiga",
    "editora": "Les Éditions de l'École",
    "colecao": "Les Lettres Latines",
    "status": "C",
    "isbn": "",
    "paginas": 0,
    "isActive": true,
    "isAntigo": false,
    "observacoes": "",
    "dataCriacao": "2023-01-26T19:42:41.895Z",
    "dataModificacao": "2023-01-26T19:42:41.915Z",
    "dataSupressao": null,
    "versao": 0
  }
  
]





