#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = http://localhost:3000

# ============================================================================
#    Entity: User
#    Endpoint: /users
# ============================================================================


####
#### Selects all users 
#### 
GET {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Create a new user 
#### 
POST {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json

[
    { 
        "nome": "Julio Cesar", 
        "sobrenome": "Torres dos Santos", 
        "email": "juliozohar@gmail.com", 
        "password": "senhamuitoforte",
        "codigoStatus": "C"
    }
]


####
#### Create a new batch of users 
#### 
POST {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json

[
    { 
        "nome": "Julio Cesar", 
        "sobrenome": "Torres dos Santos", 
        "email": "juliozohar@gmail.com", 
        "password": "senhamuitoforte",
        "codigoStatus": "C"
    }
]

####
#### Create a new batch of users 
#### 
PATCH {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json

[
    {   "codigo" : 1, 
         
            "password": "outrasenhamuitoforte"
        
    }
]