#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = http://localhost:3000

# ============================================================================
#    Entity: User
#    Endpoint: /users
# ============================================================================

####
#### Select all users 
#### 
GET {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Create a new user 
#### 
POST {{hostname}}/users HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "nome": "Paul",
    "sobrenome": "Hindenburg",
    "email": "paul.hindenburg@wehrmacht.de",
    "codigoStatus": "A"
}

